replicaCount: 1

image:
  repository: sondresjo/garge-operator
  pullPolicy: IfNotPresent
  tag: "v1.1.0"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount: {}

podAnnotations: {}

podSecurityContext: {}

securityContext: {}

service:
  type: ClusterIP
  port: 5000

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}

env: []
